name: Check Non-ASCII Character
author: Jason Lin
description: Updates Readme/specified file with latest projects information

inputs:
  gh_token:
    description: "Github Personal Access token"
    required: False

runs:
  using: "composite"
  steps:
    - run: python ${{ github.action_path }}/action.py 
      shell: bash

branding:
  icon: 'info'
  color: 'cyan'